package com.na982.opichelper.presentation.viewmodel

enum class CurrentMode {
    NONE,
    QUESTION_PLAY,
    ANSWER_PLAY,
    REPEAT_LISTENING,
    ENGLISH_WRITING,
    ENGLISH_WRITING_RECORDING,
    ENGLISH_WRITING_PLAYING,
    ENGLISH_WRITING_WITH_FILE,
    FULL_MEMORIZATION,
    FULL_MEMORIZATION_QUESTION_PLAYING,
    FULL_MEMORIZATION_RECORDING,
    FULL_MEMORIZATION_PLAYING,
    FULL_MEMORIZATION_WITH_FILE
}
