package com.na982.opichelper.domain.entity

enum class ModeGroup { NONE, REPEAT_LISTENING, ENGLISH_WRITING, FULL_MEMORIZATION }

enum class CurrentMode {
    NONE,
    REPEAT_LISTENING,
    ENGLISH_WRITING,
    ENGLISH_WRITING_RECORDING,
    FULL_MEMORIZATION,
    FULL_MEMORIZATION_QUESTION_PLAYING,
    FULL_MEMORIZATION_RECORDING,
    FULL_MEMORIZATION_PLAYING,
    FULL_MEMORIZATION_WITH_FILE;

    val group: ModeGroup get() = when (this) {
        NONE -> ModeGroup.NONE
        REPEAT_LISTENING -> ModeGroup.REPEAT_LISTENING
        ENGLISH_WRITING, ENGLISH_WRITING_RECORDING -> ModeGroup.ENGLISH_WRITING
        FULL_MEMORIZATION, FULL_MEMORIZATION_QUESTION_PLAYING, FULL_MEMORIZATION_RECORDING, FULL_MEMORIZATION_PLAYING, FULL_MEMORIZATION_WITH_FILE -> ModeGroup.FULL_MEMORIZATION
    }
}
